version: "3.8"

services:
  blue:
    image: your-dockerhub-username/qpin_server:latest
    container_name: blue
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_ENV=prod
    restart: always