version: "3.8"

services:
  green:
    image: your-dockerhub-username/qpin_server:latest
    container_name: green
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_ENV=prod
    restart: always